let worker=null,canvas,ctx,board=[],selected=null;const pieces={K:'♔',Q:'♕',R:'♖',B:'♗',N:'♘',P:'♙',k:'♚',q:'♛',r:'♜',b:'♝',n:'♞',p:'♟'};
const startPos='rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR';
document.addEventListener('DOMContentLoaded',()=>{canvas=document.getElementById('gameCanvas');ctx=canvas.getContext('2d');document.getElementById('newGameBtn').addEventListener('click',newGame);document.getElementById('aiMoveBtn').addEventListener('click',aiMove);canvas.addEventListener('click',handleClick);newGame();});
function newGame(){board=parseFEN(startPos);render();}
function parseFEN(fen){const b=[];let row=[];for(const c of fen){if(c==='/'){b.push(row);row=[];}else if(!isNaN(c)){for(let i=0;i<parseInt(c);i++)row.push('');}else row.push(c);}b.push(row);return b;}
function render(){const s=60;for(let r=0;r<8;r++)for(let c=0;c<8;c++){ctx.fillStyle=(r+c)%2===0?'#f0d9b5':'#b58863';ctx.fillRect(c*s,r*s,s,s);if(selected&&selected.r===r&&selected.c===c){ctx.fillStyle='rgba(255,255,0,0.5)';ctx.fillRect(c*s,r*s,s,s);}if(board[r][c]){ctx.fillStyle=board[r][c]===board[r][c].toUpperCase()?'#fff':'#000';ctx.font='40px serif';ctx.textAlign='center';ctx.fillText(pieces[board[r][c]]||'',c*s+s/2,r*s+s/2+12);}}}
function handleClick(e){const rect=canvas.getBoundingClientRect(),c=Math.floor((e.clientX-rect.left)/60),r=Math.floor((e.clientY-rect.top)/60);if(selected){const from=selected;selected=null;if(board[from.r][from.c]&&isValidMove(from,{r,c})){board[r][c]=board[from.r][from.c];board[from.r][from.c]='';}}else if(board[r][c])selected={r,c};render();}
function isValidMove(from,to){return from.r!==to.r||from.c!==to.c;}
function aiMove(){if(worker)worker.terminate();worker=new Worker('worker.js');worker.onmessage=e=>{if(e.data.type==='MOVE'){const{from,to}=e.data.payload;board[to.r][to.c]=board[from.r][from.c];board[from.r][from.c]='';render();document.getElementById('eval').textContent=e.data.payload.eval.toFixed(1);}};worker.postMessage({type:'FIND_MOVE',payload:{board}});}
